# Generated by Django 5.1.4 on 2025-05-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_jobrecruiter_jobdescription_vectortable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdescription",
            name="recruiter",
        ),
    ]
