services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: [ "npm", "run", "dev" ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
